[build-system]
requires = ["hatchling >= 1.26"]
build-backend = "hatchling.build"

[project.scripts]
sgfl = "sgfl.cli:app"

[project]
dependencies = ["typer", "requests", "dotenv", "django>2.0; os_name == 'nt'"]
name = "sgfl"
version = "0.0.1"
authors = [{ name = "tms2202" }]
description = "A package for managing the Stuart Games Roblox build and save workflow."
readme = "README.md"
requires-python = ">=3.9"
classifiers = [
    "Programming Language :: Python :: 3",
    "Operating System :: OS Independent",
]
license = "MIT"
license-files = ["LICEN[CS]E*"]
