[build-system]
requires = ["hatchling >= 1.26"]
build-backend = "hatchling.build"

[project.scripts]
sgfl = "sgfl.cli:app"

[project]
dependencies = ["typer", "requests", "python-dotenv"]
name = "sgfl"
version = "1.5.1"
authors = [{ name = "devvf" }]
maintainers = [{ name = "stuart-2202" }]
description = "A package for managing the Stuart Games Roblox workflow."
readme = "README.md"
requires-python = ">=3.9"
classifiers = [
    "Programming Language :: Python :: 3",
    "Operating System :: OS Independent",
]
license = "MIT"
license-files = ["LICEN[CS]E*"]
