import json
import subprocess
import requests
from sys import platform
from .util import *

def startPlace(pull:bool):
    placeId = getEnvSafe("PLACE_ID")
    universeId = getEnvSafe("UNIVERSE_ID")
    publishKey = getEnvSafe("PUBLISH_KEY")
    userId = getEnvSafe("USER_ID")

    #pull and build
    if pull:
        subprocess.run(["git", "pull"])

    runLuauFile("lua/build.luau")

    #make correct publish req to roblox
    url = f'https://apis.roblox.com/universes/v1/{universeId}/places/{placeId}/versions?versionType=Published'
    headers = {"x-api-key":publishKey,"Content-Type":"application/xml"}

    with open(PLACE_FILE_PATH,'rb') as f:
        bin = f.read()

    res = requests.post(url,headers=headers,data=bin)

    if res.status_code != 200:
        print(f"{color.BOLD}ERROR{color.END} {res.status_code}: Please fill out the {color.BOLD}.env{color.END} file.")
    else:
        placeOpenString=f"roblox-studio:1+userId:{userId}+task:EditPlace+placeId:{placeId}+universeId:{universeId}"

        #open studio (generic window)
        if platform == "win32": #windows (any ver)
            subprocess.run(["start", placeOpenString], shell=True)
        elif platform == "darwin": #macos
            subprocess.run(["open", placeOpenString])

        deleteFile(PLACE_FILE_PATH)
        deleteFile("sourcemap.json")
        subprocess.run(["code", "."], shell=True)
        subprocess.run(["rojo", "serve"])

def savePlace():
    placeId = getEnvSafe("PLACE_ID")
    downloadKey = getEnvSafe("DOWNLOAD_KEY")


    #make correct publish req to roblox
    url = f'https://apis.roblox.com/asset-delivery-api/v1/assetId/{placeId}'
    headers = {"x-api-key":downloadKey}

    res = requests.get(url,headers=headers)

    downloadUrl = json.loads(res.text)['location']

    if downloadUrl == None:
        print("Couldn't get download url to download place file")

    placeData = requests.get(downloadUrl).content

    #write to place file
    with open(PLACE_FILE_PATH,'wb') as f:
        f.write(placeData)

    runLuauFile("lua/importAssets.luau")

    deleteFile(PLACE_FILE_PATH)
    deleteFile("sourcemap.json")
    print(f"{color.BOLD}Saved place data{color.END} to the local file system.")
    
def initPlace():
    createDirIfNotExist("src")
    createDirIfNotExist("src/client")
    createDirIfNotExist("src/server")
    createDirIfNotExist("src/shared")
    createDirIfNotExist("src/shared/Util")

    open("src/client/init.client.luau",'w')
    open("src/server/init.server.luau",'w')

    assetTable = getTableFromJsonFile("json/default.assets.json")

    for _,data in assetTable.items():
        createDirIfNotExist(data["folder"])

    #https://stackoverflow.com/a/12309296
    with open('assets.json', 'w', encoding='utf-8') as f:
        json.dump(assetTable, f, ensure_ascii=False, indent=4)

    with open('default.project.json', 'w', encoding='utf-8') as f:
        fileJson = getTableFromJsonFile("json/default.project.json")
        json.dump(fileJson, f, ensure_ascii=False, indent=4)
    
    with open("README.md",'w') as f:
        f.write("Generated by SGFL!\n")

    with open(".env","w") as f:
        f.write("PLACE_ID=\n")
        f.write("UNIVERSE_ID=\n")
        f.write("PUBLISH_KEY=\n")
        f.write("DOWNLOAD_KEY=\n")
        f.write("USER_ID=")

    with open(getAbsoluteFileURI("misc/gitignore.txt"),"r") as f:
        text = f.readlines()
        with open(".gitignore","w") as g:
            g.writelines(text)

    runSilentSubprocess(["rokit", "init"])
    runSilentSubprocess(["rokit", "add","lune"])
    runSilentSubprocess(["rokit", "add","rojo"])
    runSilentSubprocess(["rokit","install"])

    print(f"🌊 {color.BOLD}Created{color.END} new sgfl instance - to get started run {color.BOLD}sgfl start{color.END}!")





